#logging.level.com.example=trace
#logging.file=springboot.logspring:
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    #url: jdbc:mysql://192.168.0.108:3306/sell?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://localhost:3306/boot2?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#  redis:
#    host: 192.168.0.108
#    port: 6379
server:
  context-path: /sell

wechat:
  #公众号id
  mpAppId: wx5271c0fec72093db
  #公众号密钥
  mpAppSecret: 246690309fedaf15eb62ac16ce12bae9
  #开放平台id
  oppenAppid:
  #开放平台密钥
  openAppSecret:

  mchId: 1509922941

  mchKey: xinqushikejiyouxiangongsi6666666
mybatis:
  check-location: classpath:mapper/.xml


#  keyPath: C:\Users\93170\Desktop\cert\apiclient_cert.p12
#
#  notifyUrl: http://sheng.natapp1.cc/sell/pay/notify
